version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: task_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge